name: build
on: push

jobs:
   build:
     runs-on: ubuntu-latest
     container:
        image: centos
     steps:
        - uses: actions/checkout@v2
        - name: use Node.js
          uses: actions/setup-node@v1
        - run: npm install react
        - run: yum update
     
